name: Run Terraform
description: Plan and apply required infrastructure changes

inputs:
  aws-access-key-id:
    description: "AWS Access Key ID"
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true
  aws-region:
    description: "AWS Region"
    default: "eu-central-1"
    required: true
  notification-email:
    description: "Notification Email"
    required: true
  s3-bucket-name:
    description: "S3 Bucket Name"
    required: true
  environment:
    description: "Environment"
    default: "Production"
    required: true

runs:
  using: "composite"
  steps:
    - uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: cd terraform && terraform init && terraform validate -no-color && terraform plan && terraform apply --auto-approve
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
