name: Verify
description: Run tests and lint

runs:
  using: 'composite'
  steps:
      - name: Lint code
        run: npm run lint
        shell: bash

      - name: Run unit tests
        run: npm run test
        shell: bash
