name: Deploy Vercel
description: Deploy Vercel for preview

inputs:
  vercel-token:
    description: "Vercel token"
    required: true
  mode:
    description: "Deployment mode"
    required: true
    default: "production"

runs:
  using: "composite"
  steps:
    - name: Install Vercel CLI
      run: npm install --global vercel@canary
      shell: bash

    - name: PREVIEW Vercel Deployment
      run: |
        vercel pull --yes --environment=preview --token=${{ inputs.vercel-token }}
        vercel build --token=${{ inputs.vercel-token }}
        DEPLOY_OUTPUT="$(vercel deploy --prebuilt --token=${{ inputs.vercel-token }})"
        DEPLOY_URL=$(echo "$DEPLOY_OUTPUT" | grep http | tail -n 1)
        echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV
      shell: bash
      env:
        VITE_ENVIRONMENT: "PREVIEW"

    - name: Comment with preview URL
      uses: actions/github-script@v7
      with:
        script: |
          const { DEPLOY_URL } = process.env;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🔍 Preview URL: ${DEPLOY_URL}`
          });

    - name: Run e2e tests
      uses: ./.github/actions/run-e2e
      with:
        base_url: ${{ env.DEPLOY_URL }}
