name: E2E Tests
description: Run e2e tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "URL of environment to test"
        required: true

runs:
  using: "composite"
  steps:
    - name: Run Playwright tests
      run: npm run test:e2e
      shell: bash
      env:
        BASE_URL: ${{ inputs.environment }}
