name: E2E Tests
description: Run e2e tests

inputs:
  base_url:
    description: "URL of environment to test"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Playwright browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps
      shell: bash

    - name: Run Playwright tests
      run: npm run test:e2e
      shell: bash
      env:
        BASE_URL: ${{ inputs.base_url }}

    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
