name: Deploy on push

on:
  push:
    branches:
      - main

jobs:
  deploy-netlify:
    uses: ./.github/workflows/deploy-netlify.yml
    secrets: inherit

  deploy-aws:
    uses: ./.github/workflows/deploy-aws.yml
    secrets: inherit
